spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_jooq_learn
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  JWT_EXPIRATION: 86400 # 24 hours
  JWT_SECRET_KEY: 7BPKL51/8VQQw+CLTD7cGek0AtWbrVyFyzRVSkaJb68=

messages:
  basename: i18n/messages
  encoding: UTF-8

