CREATE TABLE IF NOT EXISTS `tbl_users`(
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `first_name` VARCHAR(50),
    `last_name` VARCHAR(50),
    `email` VARCHAR(100),
    `password` VARCHAR(20),
     CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
     UPDATED_AT DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
     DELETED_AT DATETIME DEFAULT NULL
);